### ISSUE TITLE
context silently ignored when using describe<Class> for subcontexts.

### ISSUE THREAD

**Issue by mervyn-mccreight** [failgood/failgood#104]
Initially I tried using the convenience inline function `describe<Type>` to nest testing of inner classes to let failgood generate context descriptors.

Imagine you have a class like this:
```kotlin
data class Something(
  val inner: Inner,
) {
  data class Inner(val value: Int)
}
```

and you want to test some behavior of the `Inner` inner class, I tried to write something like:

```kotlin
// (...)
val context = describe<Something> {
  describe<Something::Inner> {
    it("test something") {
      // (...)
    }
  }
}
```

but this silently just does not invoke any tests, because the `describe<Type>` convenience function does only exist for `RootContext` level. I think this should either not compile, or be possible and execute nested tests as expected - but it should not just silently do nothing.

What do you think?

**Comment by christophsturm** [comment]
maybe the best solution for these kind of problems is to rename the top level describe method.

**Comment by christophsturm** [comment]
related to #112

**Comment by christophsturm** [comment]
I'm treating this as a bug, because even if we ever fix this with an api change it should just work now
