### ISSUE TITLE
Test not found when nested `describe`'s `subjectType` is `KClass`

### ISSUE THREAD

**Issue by dkindler** [failgood/failgood#18]
Code:
```
object TypesTest {
    val context = describe("Service types") {
        describe(PricingSolution::class) {
...
}
```

Result:
```
* Service types
0 tests. time: total:532ms cpu:2101ms, load:394%. 0 tests/sec

Process finished with exit code 0
```
---------------

Code:
```
object TypesTest {
    val context = describe("Service types") {
        describe("Pricing Soltuion") {
...
}
```

Result: Test runs

**Comment by christophsturm** [comment]
interesting, the problem here is that its using the top level describe instead of the DSL describe. In the dsl describe only takes a string. But this code should either not compile or result in a useful error message.

**Comment by christophsturm** [comment]
one easy fix would be to rename the top level method to `context(...)` (like the `val`) or maybe rename both to `suite`
