### ISSUE TITLE
display root context as failed if set-up inside the root context fails

### ISSUE THREAD

**Issue by mervyn-mccreight** [failgood/failgood#190]
If I open up a root context and let something fail initially, before even executing the first test-leaf, the test run is reported as failed, but there is no information at least inside IntelliJ about which root context failed and why, I have to look that up in the generated JUnit test report (it is present there).

I think it would be nice to have this feedback inside the IDE immediately. As far as I have seen e.g. the test-logger plugin of gradle doesn't display those failed roots, they are just missing. This leads to confusing output, because "all tests" that are displayed are displayed as green, but the run fails.

**Comment by christophsturm** [comment]
can you share a sample test that fails in that way, and a screenshot?

**Comment by mervyn-mccreight** [comment]
I'll try to reproduce it in a sample project, but I don't know if I can do it today :)

**Comment by christophsturm** [comment]
if this is still an issue please give more info.

**Comment by christophsturm** [comment]
closing because I never got more info. please reopen if you still have this problem
